### PR TITLE
PHP alterations

### PR DESCRIPTION
**Pull request by b3none**
I plan on making the PHP page a little nicer over the next few weeks, this is just the first change to get the ball rolling. Would you be okay with me doing a whole side project for it?

### CODE REVIEW

**Comment by peace-maker** [comment]
Sure, go ahead! That page was just intended to be used as a reference when adding a Top 10 list to an existing website. Not to be used verbatim.

Do you plan to create a full application for others to install on their servers? With what features?

**Comment by b3none** [comment]
At the moment I'm just thinking I'll make a fairly basic Silex app that'll just have a page for the statistics that will also have player profiles. I'm quite busy at the moment but I'll get around to it :+1:  Can we get this merged

**Comment by peace-maker** [comment]
I think a seperate repository for your app is better suited than a pull request here. I'll gladly take the cleanup, but since you didn't actually add anything yet, adding yourself to the credits list is a bit over the top.

I'll gladly add a link to your web panel to the readme once you're ready though!
I don't have a database dump available, sorry 😞

**Comment by b3none** [comment]
If this isn't getting merged can we close it? 💯

**Comment by peace-maker** [comment]
As I've mentioned in my previous comment, adding yourself to a credits list is a bit of a stretch in any situation, but even more in this case where your changes didn't contribute anything new at all. Don't get me wrong, I appreciate your help, but I think this isn't worth the trouble if you insist on your changes as it is right now.

**Pull request closed without merging**
